
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="hammer_mod"
version="4.0.3"
displayName="Hammer Additions" #mandatory
logoFile = "hammer_addition_title.png"
authors="${mod_authors}" #optional
description='''${mod_description}'''


[[dependencies.hammer_mod]]

    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.hammer_mod]]
    modId="minecraft"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
